### ISSUE TITLE
Problème de blog

### ISSUE THREAD

**Issue by GuyliannEngels** [carineboukeng/carineboukeng.blog#1]
@carineboukeng,

Sur ton dépôt github aucun fichier n est à jour. Tu dois faire des commit des push

**Comment by carineboukeng** [comment]
Je l'ai fais lors de la derniere science de cours mais je n' ai pas retrouvé mon blog
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 25 octobre 2019 05:53:34
À : carineboukeng/carineboukeng.blog <carineboukeng.blog@noreply.github.com>
Cc : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : [carineboukeng/carineboukeng.blog] Problème de blog (#1)


@carineboukeng<https://github.com/carineboukeng>,

Sur ton dépôt github aucun fichier n est à jour. Tu dois faire des commit des push

**Comment by GuyliannEngels** [comment]
De ce que je vois tu ne l a pas fait. Tu dois aller dans ton projet lié au  blog et puis faire ton commit et ton push

UMONS

___________________________________
Guyliann Engels
Assistant/ Research and teaching assistant

Université de Mons / University of Mons
Service d'Ecologie numérique des milieux aquatiques / Numerical Ecology of Aquatic Systems Laboratory
6, Avenue du Champ de Mars, Pentagone, 3D21
7000 Mons
+32(0)65/37 34 78

________________________________

**Comment by carineboukeng** [comment]
Justement je ne trouve pas ce projet
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 25 octobre 2019 06:03:09
À : carineboukeng/carineboukeng.blog <carineboukeng.blog@noreply.github.com>
Cc : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [carineboukeng/carineboukeng.blog] Problème de blog (#1)

De ce que je vois tu ne l a pas fait. Tu dois aller dans ton projet lié au blog et puis faire ton commit et ton push

UMONS

___________________________________
Guyliann Engels
Assistant/ Research and teaching assistant

Université de Mons / University of Mons
Service d'Ecologie numérique des milieux aquatiques / Numerical Ecology of Aquatic Systems Laboratory
6, Avenue du Champ de Mars, Pentagone, 3D21
7000 Mons
+32(0)65/37 34 78

________________________________

**Comment by GuyliannEngels** [comment]
Sur quelle machine travailles tu ? Une du labo ? Toujours la même ?

**Comment by carineboukeng** [comment]
J'avais travaillé ce jour avec une machine de l'université en sale de cours
________________________________
De : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>
Envoyé : vendredi 25 octobre 2019 06:05:21
À : carineboukeng/carineboukeng.blog <reply@reply.github.com>
Objet : RE: [carineboukeng/carineboukeng.blog] Problème de blog (#1)

Justement je ne trouve pas ce projet
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 25 octobre 2019 06:03:09
À : carineboukeng/carineboukeng.blog <carineboukeng.blog@noreply.github.com>
Cc : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [carineboukeng/carineboukeng.blog] Problème de blog (#1)

De ce que je vois tu ne l a pas fait. Tu dois aller dans ton projet lié au blog et puis faire ton commit et ton push

UMONS

___________________________________
Guyliann Engels
Assistant/ Research and teaching assistant

Université de Mons / University of Mons
Service d'Ecologie numérique des milieux aquatiques / Numerical Ecology of Aquatic Systems Laboratory
6, Avenue du Champ de Mars, Pentagone, 3D21
7000 Mons
+32(0)65/37 34 78

________________________________

**Comment by carineboukeng** [comment]
Non ce n'etait pas avec la meme machine
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 25 octobre 2019 06:07:54
À : carineboukeng/carineboukeng.blog <carineboukeng.blog@noreply.github.com>
Cc : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [carineboukeng/carineboukeng.blog] Problème de blog (#1)


Sur quelle machine travailles tu ? Une du labo ? Toujours la même ?

**Comment by GuyliannEngels** [comment]
Il va donc falloir retourner sur la machine que tu avais utilisé ce jour là.

Si tu n avais pas édité grand chose, tu peux cloner à nouveau ton dépôt et recommencer sur une autre machine

**Comment by carineboukeng** [comment]
Je n'avais pas fais grand chose
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 25 octobre 2019 06:41:33
À : carineboukeng/carineboukeng.blog <carineboukeng.blog@noreply.github.com>
Cc : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [carineboukeng/carineboukeng.blog] Problème de blog (#1)


Il va donc falloir retourner sur la machine que tu avais utilisé ce jour là.

Si tu n avais pas édité grand chose, tu peux cloner à nouveau ton dépôt et recommencer sur une autre machine

**Comment by GuyliannEngels** [comment]
Dans ce cas, tu pourrais cloner ton dépot sur la machine que tu utile actuellement et éditer ton blog

**Comment by carineboukeng** [comment]
Merci Mr le probleme a eté resolu.  Bonne journée
________________________________
De : Guyliann Engels <notifications@github.com>
Envoyé : vendredi 25 octobre 2019 07:19:23
À : carineboukeng/carineboukeng.blog <carineboukeng.blog@noreply.github.com>
Cc : Carine ANAGMO BOUKENG <Carine.ANAGMOBOUKENG2@student.umons.ac.be>; Mention <mention@noreply.github.com>
Objet : Re: [carineboukeng/carineboukeng.blog] Problème de blog (#1)


Dans ce cas, tu pourrais cloner ton dépot sur la machine que tu utile actuellement et éditer ton blog
